[general]
import = ["themes/noctalia.toml"]


[window]
opacity = 0.90

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[colors.primary]
background = '#191724'
foreground = '#e0def4'

[colors.cursor]
text = '#e0def4'
cursor = '#524f67'

[colors.vi_mode_cursor]
text = '#e0def4'
cursor = '#524f67'

[colors.selection]
text = '#e0def4'
background = '#403d52'

[colors.normal]
black = '#26233a'
red = '#eb6f92'
green = '#31748f'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

[colors.bright]
black = '#6e6a86'
red = '#eb6f92'
green = '#31748f'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

[colors.hints]
start = {foreground = '#908caa', background = '#1f1d2e' }
end = { foreground = '#6e6a86', background = '#1f1d2e' }

# [general]
# import = [
#     "~/.config/alacritty/themes/rose-pine.toml"
# ]
