
[window]
opacity = 0.90

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[general]
import = [
    "~/.config/alacritty/themes/themes/rose-pine.toml"
]
